# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppMusic
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'GooglePlaces'
	pod 'GoogleMaps'
	pod 'iCarousel'
	pod 'LGSideMenuController'
	pod 'Alamofire', '~> 4.9'
	pod 'KVLoading', '~> 1.5'

  target 'AppMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppMusicUITests' do
    # Pods for testing
  end

end
